
#Port Configuration

server:
  port: 8081

#context Path
  servlet:
    context-path: /userservice

#Mysql Hiberbate Properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userservice
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


#Spring JPA Properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
